import google.generativeai as genai
from datetime import datetime
import streamlit as st

# --- CONFIGURATION ---
genai.configure(api_key="AIzaSyAbXv94hwzhbrxhBYq-zS58LkhKZQ6cjMg")
model = genai.GenerativeModel("gemini-2.0-flash")

# --- STREAMLIT SETUP ---
st.set_page_config(page_title="Quantora AI News Digest", layout="wide")

# --- HEADER UI ---
today = datetime.now().strftime("%B %d, %Y")
st.markdown(f"""
    <div style='text-align: center; padding: 10px 0 20px 0;'>
        <h1 style='font-size: 3em; margin-bottom: 0;'>🧠 Quantora AI News Digest</h1>
        <p style='color: gray; font-size: 1.2em;'>The most powerful news summary for <strong>{today}</strong></p>
        <p style='font-size: 0.9em; color: #888;'>Generated by Quantora AI</p>
    </div>
""", unsafe_allow_html=True)

# --- DYNAMICALLY DATED PROMPT ---
prompt = f"""
You are Quantora AI, a cutting-edge real-time news analysis system. Give the MOST Trending news for {today}. Create the top news digest for {today} based on live global and Indian events, using a professional journalist tone.

Structure your summary into the following categories:

1. 🔴 Topic - 1 (2 detailed paragraphs)
2. 💰 Topic - 2 (1 paragraph)
3. 🏙️ Topic - 3 (2–3 bullet points)
4. 🏛️ Topic - 4 (2–3 bullet points)
5. 🎬 Topic - 5 (2–3 bullet points)
6. 🌍 Topic - 6 (1 paragraph)

Only include realistic and relevant news that would appear on Aaj Tak, ABP News, Zee News, and BBC for {today}.
"""

# --- GENERATE NEWS ---
with st.spinner("🔍 Quantora AI is gathering and analyzing today's global news..."):
    response = model.generate_content(prompt)
    news = response.text

# --- DISPLAY NEWS WITH BLACK TEXT (NO IMAGES) ---
news_lines = news.split('\n\n')
for line in news_lines:
    if line.strip():  # Skip empty lines
        # Display the news text
        st.markdown(f"""
        <div style="background-color: #ffffff; padding: 20px; border-radius: 12px; box-shadow: 0 0 12px rgba(0,0,0,0.08); font-size: 1.1em; line-height: 1.8; color: #000000;">
            <p>{line}</p>
        </div>
        """, unsafe_allow_html=True)

# --- FOOTER ---
st.markdown("---")
st.markdown("""
    <div style='text-align: center; font-size: 0.85em; color: gray; padding-top: 10px;'>
        🔹 Powered by Quantora AI • Delivering Intelligence, Not Just Information.
    </div>
""", unsafe_allow_html=True)
